server:
  port: 8087
spring:
  application:
    name: service
  datasource:
    url: jdbc:mysql://47.98.136.216:3306/gehua?useUnicode=true&characterEncoding=utf8
    username: root
    password: wj@110120
  rabbitmq:   #rabbitmq客户端
    host: 47.98.136.216
    username: admin
    password: admin
    virtual-host: /gehua
  redis:
    host: 122.225.58.118
    password: U#rNFRkk3vuCKcZ5
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




